### ISSUE TITLE
上传图片会卡住

### ISSUE THREAD

**Issue by KeepNaivety3** [normalx/BYR_auto_upload_image#1]
![屏幕截图 2023-04-21 174024](https://user-images.githubusercontent.com/101695437/233603689-8a3c5d38-c1f3-4ba7-b2dd-c375b467e123.png)

上传图片会卡在“正在上传图片”状态，此时图片应该已经上传完成，点击检查会和站内进行对比，并显示“BYR服务器上存在以下图片，你可以使用该图片发种”。还有前几天byr更新后这个脚本和新番脚本都居中了，不知道为啥

**Comment by Xzonn** [comment]
BYR 最近更新了后端代码，原有的匹配正则表达式会失效。提了个 PR (#2)，可以修复这个问题。

**Comment by luziyan0810** [comment]
> BYR 最近更新了后端代码，原有的匹配正则表达式会失效。提了个 PR (#2)，可以修复这个问题。

感谢 pr，前阵子调整项目结构的时候在移除域名的时候把 ckfinder 的 baseURL 改成了相对的，已经调整为 '/ckfinder/...'<br>https://github.com/normalx/BYR_auto_upload_image/commit/779b39566ed1953b99f424d4b699cdf3bcc6713f
